import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	// The current official sample plugin's entry point (it moved out of the repo root).
	entryPoints: ['src/main.ts'],
	// bundle: true pulls js-yaml (a real runtime dependency) into main.js. Obsidian loads
	// exactly one file, so nothing outside main.js exists at runtime.
	bundle: true,
	external: [
		// Provided by Obsidian at runtime.
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		// Node builtins are NOT available on iOS/Android. Marking them external means any
		// accidental use survives the build and throws only on the phone — grep the built
		// main.js for require("crypto") / require("fs") / Buffer before shipping.
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
